### ISSUE TITLE
Search results doesn't show some letters

### ISSUE THREAD

**Issue by eplusg-zz** [xeric/alfred-outlook#1]
Hi,

Tried this workflow and I noticed that some letters won't show up when searching.
For example all ÅÄÖ letters are gone.

**Comment by xeric** [comment]
Yes, I can reproduce this issue, I'm confused since I was handling unicode in my script already such as some east characters like Chinese, Japanese, it could handle well, but do not know why åàā can't.
I'm still working on troubleshooting.

**Comment by xeric** [comment]
I've fixed this issue at this commit:
https://github.com/xeric/alfred-outlook/commit/56e7b3fe29fd8761b8b1cd5adfced5b3eb1bb72d

You can get new released workflow package here:
https://github.com/xeric/alfred-outlook/releases/tag/0.0.6

**Comment by eplusg-zz** [comment]
Hi @xeric ,

Tried the new version but I still seem to have same bug, å ä ö missing.

**Comment by xeric** [comment]
@Schvifty, could you please provide some information with below steps:
1. goto Alfred Preferences -> Workflows and choose Outlook Search in sidemenu
2. click most right 'bug' icon button in main windows toolbar to step into debug mode
3. try to trigger Alfred input with your hotkey and input 'å' and something else, you will get some debug information in debug console.

I test this in my local with below:
I send a mail to my self with subject 'ÅÄÖ test', and after that, I try to use 'olk Å test', that mail I sent to myself is in list of search result.

I can't reproduce this issue again with latest version, if you could provide such debug information, it should be great for me to find the root cause, please anonymize some sensitive information in debug info you got:)

**Comment by xeric** [comment]
I keep this issue open for collecting more information.
Please try latest version if you face similar issue since it works well on my laptop.

**Comment by eplusg-zz** [comment]
Hi @xeric , I did as you described and I can now see that email titles shows correct letters but the body text (text below the title) is missing ÅÄÖ.

Here is a log when I did a search:
```
# [2019-01-21 10:20:34][STDERR: input.scriptfilter] .
10:20:34 workflow.py:2055 DEBUG    ---------- Outlook Search (0.0.6) ----------
10:20:34 main.py:30 INFO     searching mail with keyword
10:20:34 workflow.py:1462 DEBUG    reading settings from /Users/testuser/Library/Application Support/Alfred 3/Workflow Data/com.xericwei.alfred/settings.json
10:20:34 workflow.py:2248 DEBUG    set last run version: 0.0.6
10:20:34 workflow.py:2097 DEBUG    ---------- finished in 0.031s ----------
[2019-01-21 10:20:34][STDERR: input.scriptfilter] .
10:20:34 workflow.py:2055 DEBUG    ---------- Outlook Search (0.0.6) ----------
10:20:34 main.py:30 INFO     searching mail with keyword
10:20:34 workflow.py:1462 DEBUG    reading settings from /Users/testuser/Library/Application Support/Alfred 3/Workflow Data/com.xericwei.alfred/settings.json
10:20:34 workflow.py:2248 DEBUG    set last run version: 0.0.6
10:20:34 workflow.py:2097 DEBUG    ---------- finished in 0.031s ----------
[2019-01-21 10:20:34][STDERR: input.scriptfilter] .
10:20:34 workflow.py:2055 DEBUG    ---------- Outlook Search (0.0.6) ----------
10:20:34 main.py:45 INFO     /Users/testuser/Library/Group Containers/UBF8T346G9.Office/Outlook/Outlook 15 Profiles/Main Profile/Data/
10:20:34 main.py:52 INFO     query string is: test
10:20:34 main.py:53 INFO     query page is: 0
10:20:34 workflow.py:1565 DEBUG    no data stored for `pagesize`
10:20:34 workflow.py:1565 DEBUG    no data stored for `folder`
10:20:34 main.py:166 INFO     query by subject, content and testuser
10:20:34 main.py:167 INFO     [u'test']
10:20:34 main.py:204 INFO     Select Message_NormalizedSubject, Message_StestuserList, Message_Preview, PathToDataFile, Message_TimeSent
        from Mail 
        where (Message_NormalizedSubject LIKE ? ) OR (Message_StestuserList LIKE ? ) OR (Message_Preview LIKE ? )  
        ORDER BY Message_TimeSent DESC 
        LIMIT ? OFFSET ?
        
10:20:34 main.py:205 INFO     (u'%test%', u'%test%', u'%test%', 20, 0)
10:20:34 main.py:91 INFO     ÅÄÖ test
10:20:34 main.py:91 INFO     ÅÄÖ test
10:20:34 main.py:91 INFO     Test email
10:20:34 main.py:91 INFO     Testing letters
10:20:34 main.py:30 INFO     searching mail with keyword
10:20:34 workflow.py:1462 DEBUG    reading settings from /Users/testuser/Library/Application Support/Alfred 3/Workflow Data/com.xericwei.alfred/settings.json
10:20:34 workflow.py:2248 DEBUG    set last run version: 0.0.6
10:20:34 workflow.py:2097 DEBUG    ---------- finished in 0.061s ----------
```

**Comment by xeric** [comment]
@Schvifty I see, my bad that forget to convert mail body, I will fix it.

**Comment by xeric** [comment]
@Schvifty thanks for your great help, I update a release 0.0.7 which fix such character display in result.
please refer here: 
https://github.com/xeric/alfred-outlook/releases/tag/0.0.7

**Comment by eplusg-zz** [comment]
> @Schvifty thanks for your great help, I update a release 0.0.7 which fix such character display in result.
> please refer here:
> https://github.com/xeric/alfred-outlook/releases/tag/0.0.7

Good job now it is working!! 👍  :)
