### ISSUE TITLE
Can you provide  Release 0.1.9 workflow download file? 

### ISSUE THREAD

**Issue by gaotianlin2998** [xeric/alfred-outlook#12]
Can you provide  Release 0.1.9 workflow download file?

**Comment by roberdorfer** [comment]
That'd be really nice, I've also noticed the lack of it.

**Comment by xeric** [comment]
That is really wired Github made something wrong, the file was there but not show on release page.
Anyway, I've updated the 0.1.9 release and upload the workflow file again.
