### ISSUE TITLE
Display all "new" emails

### ISSUE THREAD

**Issue by andyjohansson** [xeric/alfred-outlook#3]
Hi, me and almost everyone else is trying to minimize email to get "real work" done.
A situation that often occurs is that someone is calling / chatting or walking by and saying "I just sent you an email, can you take a look at it". Therefor it would be nice to not be forced to open Outlook and maybe get sucked into more email and just have a command to display the last X emails that have been received and / or display the emails that have been received within a timeframe. Is this possible to do?

**Comment by andyjohansson** [comment]
Ideas:
olk received / olk inbox (display the latest emails in the inbox)
olk received:5 (display the 5 latest emails received)
olk received:today (display the emails received today)

**Comment by xeric** [comment]
Thanks for raising such great idea, @andyjohansson let me have a think the end to end scenarios, will be updated back to you.

**Comment by xeric** [comment]
@andyjohansson I'm happy to tell you I've released [v0.1.5](https://github.com/xeric/alfred-outlook/releases/tag/0.1.5) to support your requirement.
Now you can use olk recent:{n} to get recent unread mails, n can be a number to get exact number of unread mails or 'today' to get all today's unread mails.
You can also apply some keywords to do simple filtering, like:
olk recent:today whatsit
