### ISSUE TITLE
Outlook 365 Contact Search

### ISSUE THREAD

**Issue by Chrimal** [xeric/alfred-outlook#4]
Installed workflow with good results however,
OLKP is not providing any results, running Office 365?

**Comment by xeric** [comment]
Just confirm: could you see contacts in your outlook, people tab?
you can find it in the bottom of left panel.

**Comment by Chrimal** [comment]
Hi,

This is the screen grab from outlook contacts:
[cid:image001.png@01D52689.E842E1D0]

From Outlook mail:
[cid:image002.png@01D52689.E842E1D0]

From Alfred:
[cid:image003.png@01D52689.E842E1D0]

Hope this makes sense, not sure why it is happening?

Thanks

Christian

**Comment by xeric** [comment]
Hi Chrimal,
Thanks for that you are trying to provide visual screenshots, but seems attachments could not work in github issue discussion thread. could you please send it to my personal email? flashot(AT)gmail.com.

**Comment by xeric** [comment]
as discussed in email, this is because plugin can't search server contact of outlook exchange.
OLKP was designed for search local store 'people' only.
