### ISSUE TITLE
Support send new mail without switching to Outlook app

### ISSUE THREAD

**Issue by xeric** [xeric/alfred-outlook#5]
https://www.alfredforum.com/topic/11320-workflow-for-outlook-v16-search/?do=findComment&comment=69782

As raised in this post, I open an ticket for tracking if I can find way to do it.

**Comment by multicolorist** [comment]
Hmm so I just tried using BetterTouchTool for this, and when doing the standard "Send Shortcut to Specific App" it works great without focusing the main Outlook app!

I first send the shortcut and then launch the app to make the window appear in front. See the attached pictures for how it's set-up. I'm not sure how BTT is actually sending the shortcuts though.
![Screenshot 2019-08-27 at 09 15 19](https://user-images.githubusercontent.com/8113511/63749279-64f12980-c8ab-11e9-96e1-c5771b2b81df.png)

**Comment by xeric** [comment]
As you know, BTT is a native application run can write any kind of native logic to do things, there may be some API that OS provided to invoke application I guess, but inside Alfred app, we do not have such powerful implementation to do complex logic, Alfred plugin is still running above a plugin context of Alfred App with a Python 2.

I've found some applescript api which can call send email API that provided by Microsoft Outlook, but it will popup a confirm window first time in Outlook because of security reason.
I'll implement one version and check with you if it is what you want.

**Comment by xeric** [comment]
I've almost done the feature development, and have local test for it.
The only thing we should take care is when first time we using olknew to send a mail in inline mode, Outlook will popup a warning dialog tell you some security hint, like below screenshot, just check the 'Don't show this message again' and next time you won't get this dialog again.
![image](https://user-images.githubusercontent.com/190927/64246126-ce71d780-cf3e-11e9-9b60-6ea0f311dccd.png)

One more thing is: to get best use experience, I limited this feature only works in Alfred 3+ version, for V2 I will disable this feature.

**Comment by xeric** [comment]
@multicolorist Released
https://github.com/xeric/alfred-outlook/releases/tag/0.1.6

**Comment by multicolorist** [comment]
Thanks a lot xeric! Works great, love to be able to use pure Alfred instead of going into the Outlook monolith :) 
The compromise with no GUI is already fine, as I'm guessing getting the compose-window to open would indeed activate the main Outlook window as well?
