### ISSUE TITLE
[feature request] download email attachment

### ISSUE THREAD

**Issue by sparkbold** [xeric/alfred-outlook#7]
Would it be possible to download attachment from the first result? I am trying to automate download the attachment from a specific sender to a local/network folder when the mail arrive.

**Comment by xeric** [comment]
Thanks for submit requirement, let me try.

**Comment by xeric** [comment]
I have a very tough block that I can't convert a message ID to an outlook message object, I'm still keeping trying to find solution.

**Comment by xeric** [comment]
Hi @sparkbold , I just released version [https://github.com/xeric/alfred-outlook/releases/tag/0.1.8](https://github.com/xeric/alfred-outlook/releases/tag/0.1.8) which supports attachment download on any of searched email if it contains attachment(s), for more details, you can refer to Readme file.

**Comment by xeric** [comment]
Feature provided, close.
